version: '3.8'
services:
  # Frontend container
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - brainbytes-net

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/brainbytes
      - JWT_SECRET=xWaxbtieWMd6BXtarZjnElklb1bnM9LMlDpzG1aFLAo=
      - HUGGINGFACE_TOKEN='your token'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - brainbytes-net

  # MongoDB container
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - brainbytes-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  brainbytes-net:
    driver: bridge

volumes:
  mongo-data:
