name: BrainBytes CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Setup Node.js with proper caching
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'  # This enables automatic npm caching
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci
      
    # Build the project
    - name: Build
      run: npm run build
      
    # Run tests
    - name: Test
      run: npm test
