name: BrainBytes Deploy

on:
  push:
    branches: [main, development]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'  # Updated to supported LTS version
          cache: 'npm'  # Added npm caching

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Prepare deployment
        run: |
          echo "DEPLOY_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "DEPLOY_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Deploy to Oracle Cloud
        env:
          OCI_SSH_KEY: ${{ secrets.OCI_SSH_KEY }}
          OCI_SSH_USER: ${{ secrets.OCI_SSH_USER }}
          OCI_SSH_HOST: ${{ secrets.OCI_SSH_HOST }}
        run: |
          echo "Deploying to Oracle Cloud..."
          ssh -o StrictHostKeyChecking=no $OCI_SSH_USER@$OCI_SSH_HOST << EOF
            cd /opt/brainbytes
            docker-compose pull
            docker-compose up -d --remove-orphans
          EOF

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          sleep 30  # Wait for containers to start
          curl --retry 5 --retry-delay 10 --max-time 5 \
            http://${{ secrets.OCI_SSH_HOST }}:3000/health || \
            (echo "Health check failed" && exit 1)
