name: BrainBytes Deploy

on:
  push:
    branches: [main, development]
  workflow_dispatch:

# Add to the existing workflow
  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "$HOME/lib/oracle-cli/bin" >> $GITHUB_PATH
      
      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          
          cat > ~/.oci/config << EOF
          [DEFAULT]
          user=${{ secrets.OCI_USER }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_TENANCY }}
          region=${{ secrets.OCI_REGION }}
          key_file=~/.oci/oci_api_key.pem
          EOF
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $(oci compute instance get --instance-id ${{ secrets.INSTANCE_OCID }} | jq -r '.data."public-ip"') >> ~/.ssh/known_hosts
      
      - name: Deploy to Oracle Cloud
        run: |
          INSTANCE_IP=$(oci compute instance get --instance-id ${{ secrets.INSTANCE_OCID }} | jq -r '.data."public-ip"')
          ssh opc@$INSTANCE_IP "cd ~/brainbytes && git pull && docker-compose down && docker-compose build && docker-compose up -d"

